import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PrimeReactProvider } from "primereact/api";
import 'primereact/resources/themes/lara-light-blue/theme.css';
import "./globals.css";
const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const cx = (...classes: any[]) => classes.filter(Boolean).join(' ');

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
          className={cx(
            'text-black bg-white',
            font.className,
          )}>
      <body className="antialiased bg-white max-w-3xl mb-40 flex flex-col md:flex-row mx-4 mt-8 lg:mx-auto">
        <PrimeReactProvider>
          <main className="flex-auto min-w-0 mt-6 flex flex-col px-2 md:px-0">
          {children}
          </main>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
